language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - liblapack-dev
      - g++-4.8
node_js:
  - "0.12"
  - "0.10"
  - "4"
  - "5"
sudo: false
